### ISSUE TITLE
メモリリーク脆弱性

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/named-pipe#1]
get_bufferは永遠にたまり続けるので、これはメモリリーク脆弱性である。

また、ユーザがget_bufferを操作するとタイミングによってデータ消失を招く危険があるため、getNewMessageList()で適切に対処することが望まれる。

この関数はコメントにおいて「最後の呼び出し以降に」とあるが、実装とは一致していないようである。

**Comment by yncat** [comment]
オブジェクトの破棄で消えるので、実際にはメモリリークではないですが、get_bufferをクリアしていないのは単純に間違ってますね。なおします
