### ISSUE TITLE
4095バイト目が文字の途中だとエラーとなる

### ISSUE THREAD

**Issue by yamahubuki** [actlaboratory/named-pipe#6]
# 事象

大きな文字列を読み込むにあたり、4095バイト目が文字の途中となる場合(4095～4096バイト目で1文字を形成するような場合)にデコードエラーとなってしまいます。

# 原因

内部でwin32file.ReadFile()を用いて4096バイトを取得し、それを単体でデコードしてからバッファにためる構造のため

# やりたいこと

PDFtoTextした結果をファイルにしか書き込めないコマンドラインアプリケーションがあるので、出力ファイル名のところにパイプを指定してやることで、このコマンドラインツールからの出力を取得する

# 改善に向けて

バイナリからテキストへの返還にストリームとかを使わないと厳しそうな気がします

**Comment by yncat** [comment]
事象としては把握したので、週末にどうにかやってみます。
